\set ON_ERROR_STOP on
BEGIN;
CREATE TYPE education_form AS ENUM ('очное', 'заочное', 'очно-заочное');
CREATE TYPE gender AS ENUM ('М', 'Ж');
CREATE TYPE funding_type AS ENUM ('бюджет', 'платное');
CREATE TYPE student_status AS ENUM ('числится', 'академический отпуск', 'отчислен', 'выпустился');
CREATE TYPE control_form_t AS ENUM ('экзамен', 'зачёт', 'курсовая', 'дифференцированный зачёт');
CREATE TYPE lesson_type_t AS ENUM ('лекция', 'семинар', 'лабораторная', 'практика');
CREATE TYPE attendance_t AS ENUM ('присутствовал', 'отсутствовал', 'опоздал', 'уважительная причина');
CREATE TYPE assignment_t AS ENUM ('лабораторная', 'контрольная', 'курсовая', 'реферат', 'проект', 'коллоквиум');

CREATE TABLE ROLES (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE DEPARTMENTS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE,
  FACULTY TEXT NOT NULL
);

CREATE TABLE MAJORS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME TEXT NOT NULL UNIQUE,
  CODE TEXT
);

CREATE TABLE USERS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  MIDDLE_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) UNIQUE,
  PHONE VARCHAR(10) UNIQUE,
  PASSWORD TEXT NOT NULL,
  ROLE_ID SMALLINT NOT NULL REFERENCES ROLES(ID)
);

CREATE TABLE TEACHERS (
  USER_ID INTEGER PRIMARY KEY REFERENCES USERS(ID) ON DELETE CASCADE,
  DEPARTMENT_ID INTEGER REFERENCES DEPARTMENTS(ID),
  POSITION TEXT,
  DEGREE TEXT
);

CREATE TABLE GROUPS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE,
  MAJOR_ID INTEGER REFERENCES MAJORS(ID),
  YEAR SMALLINT,
  EDUCATION_FORM EDUCATION_FORM,
  ENROLLMENT_YEAR SMALLINT,
  SUPERVISOR_ID INTEGER REFERENCES TEACHERS(USER_ID)
);

CREATE TABLE STUDENTS (
  USER_ID INTEGER PRIMARY KEY REFERENCES USERS(ID) ON DELETE CASCADE,
  DATE_OF_BIRTH DATE,
  GENDER GENDER,
  GROUP_ID INTEGER REFERENCES GROUPS(ID),
  FUNDING_TYPE FUNDING_TYPE,
  STATUS STUDENT_STATUS NOT NULL DEFAULT 'числится',
  ENROLLMENT_DATE DATE
);

CREATE TABLE SUBJECTS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME TEXT NOT NULL,
  DESCRIPTION TEXT,
  HOURS_LECTURES INT NOT NULL DEFAULT 0,
  HOURS_SEMINARS INT NOT NULL DEFAULT 0,
  HOURS_LABS INT NOT NULL DEFAULT 0,
  CONTROL_FORM CONTROL_FORM_T,
  DEPARTMENT_ID INT REFERENCES DEPARTMENTS(ID)
);

CREATE TABLE COURSE_ASSIGNMENTS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  GROUP_ID INT NOT NULL REFERENCES GROUPS(ID),
  SUBJECT_ID INT NOT NULL REFERENCES SUBJECTS(ID),
  TEACHER_ID INT NOT NULL REFERENCES TEACHERS(USER_ID),
  TERM SMALLINT NOT NULL,
  ACADEMIC_YEAR TEXT NOT NULL,
  UNIQUE (GROUP_ID, SUBJECT_ID, TERM, ACADEMIC_YEAR)
);

CREATE TABLE LESSONS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COURSE_ASSIGNMENT_ID INT NOT NULL REFERENCES COURSE_ASSIGNMENTS(ID) ON DELETE CASCADE,
  LESSON_TYPE LESSON_TYPE_T NOT NULL,
  LESSON_DATE DATE NOT NULL,
  START_TIME TIME NOT NULL,
  END_TIME TIME NOT NULL,
  ROOM TEXT
);

CREATE TABLE ATTENDANCE (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  LESSON_ID INT NOT NULL REFERENCES LESSONS(ID) ON DELETE CASCADE,
  STUDENT_ID INT NOT NULL REFERENCES STUDENTS(USER_ID) ON DELETE CASCADE,
  STATUS ATTENDANCE_T NOT NULL DEFAULT 'присутствовал',
  UNIQUE (LESSON_ID, STUDENT_ID)
);

CREATE TABLE ASSIGNMENTS (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  COURSE_ASSIGNMENT_ID INT NOT NULL REFERENCES COURSE_ASSIGNMENTS(ID) ON DELETE CASCADE,
  TITLE TEXT NOT NULL,
  TYPE ASSIGNMENT_T NOT NULL,
  COEFFICIENT NUMERIC(4,2) NOT NULL DEFAULT 1.00,
  MAX_GRADE SMALLINT NOT NULL DEFAULT 5
);

CREATE TABLE GRADES (
  ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  STUDENT_ID INT NOT NULL REFERENCES STUDENTS(USER_ID) ON DELETE CASCADE,
  COURSE_ASSIGNMENT_ID INT NOT NULL REFERENCES COURSE_ASSIGNMENTS(ID) ON DELETE CASCADE,
  ASSIGNMENT_ID INT REFERENCES ASSIGNMENTS(ID) ON DELETE SET NULL,
  GRADE NUMERIC(3, 1),
  GRADED_BY INT REFERENCES TEACHERS(USER_ID),
  GRADED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (STUDENT_ID, COURSE_ASSIGNMENT_ID, ASSIGNMENT_ID)
);
COMMIT;